# Generated by Django 5.0.3 on 2024-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_achievements_user_id_achievements_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
