# Generated by Django 5.0.3 on 2024-05-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_achievements_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='image',
            new_name='file',
        ),
    ]
