# Generated by Django 5.0.3 on 2024-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_achievements_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='preview',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
