# Generated by Django 5.0.3 on 2024-06-07 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_avatar_profile_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='likes',
        ),
        migrations.AddField(
            model_name='achievements',
            name='likes',
            field=models.ManyToManyField(related_name='achievement_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
