# Generated by Django 5.0.3 on 2024-06-11 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_avatar_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'ogg', 'mp3'])]),
        ),
    ]
