# Generated by Django 5.0.3 on 2024-06-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_achievements_file'),
        ('main', '0010_remove_achievements_likes_achievements_likes'),
    ]

    operations = [
    ]
