# Generated by Django 5.0.3 on 2024-06-11 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_achievements_liked_users_remove_achievements_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='views_users',
            field=models.ManyToManyField(blank=True, related_name='views_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
