# Generated by Django 5.0.3 on 2024-06-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_achievements_liked_by'),
        ('main', '0013_achievements_views_users'),
    ]

    operations = [
    ]
